/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleReserva;
import controller.ControleReservaProduto;
import controller.ControleProduto;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.ListIterator;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;

import model.Produto;
import model.Reserva;
import model.ReservaProduto;

import util.ReservaProdutoTableModel;
import util.ProdutoTableModel;

public class AtualizarReserva extends javax.swing.JFrame {

    private String produtoNome;
    private ControleProduto controleProd = new ControleProduto();
    private List<Produto> listaProd = controleProd.listarProdutos("");

    private ProdutoTableModel modelProduto = new ProdutoTableModel(listaProd);
    private Produto p = new Produto();
    
    private List<ReservaProduto> listaReserva;
    private ControleReservaProduto controleRP = new ControleReservaProduto();
    private ReservaProdutoTableModel modelRP;
    
    private ControleReserva controleReserva = new ControleReserva();
    private Reserva reserva = new Reserva();
    
    public AtualizarReserva(Reserva r) {
        initComponents();
        this.reserva = r;
        tabelaProduto.setModel(modelProduto);
        this.listaReserva = controleRP.listarRP(this.reserva);
        this.modelRP = new ReservaProdutoTableModel(listaReserva);
        tabelaProdutosReservados.setModel(modelRP);
        totalTxt.setText(""+this.reserva.getPreco());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        qtdRemover = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutosReservados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        RemoverProd = new javax.swing.JButton();
        RegistrarPedido = new javax.swing.JButton();
        AdicionarProd = new javax.swing.JButton();
        buscaProduto = new javax.swing.JTextField();
        qtdProduto = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        totalTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("LISTA DE PRODUTOS DA RESERVA");

        tabelaProdutosReservados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaProdutosReservados);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL:");

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaProduto);

        RemoverProd.setText("REMOVER PRODUTO");
        RemoverProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverProdActionPerformed(evt);
            }
        });

        RegistrarPedido.setText(" ALTERAR RESERVA");
        RegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPedidoActionPerformed(evt);
            }
        });

        AdicionarProd.setText("ADICIONAR PRODUTO");
        AdicionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarProdActionPerformed(evt);
            }
        });

        buscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaProdutoActionPerformed(evt);
            }
        });
        buscaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscaProdutoKeyReleased(evt);
            }
        });

        jLabel6.setText("Produto:");

        Cancelar.setText("CANCELAR ALTERAÇÃO");
        Cancelar.setActionCommand("CANCELAR ALTERAÇÃO");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        totalTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        totalTxt.setText("R$ 0,00");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ALTERAR RESERVA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                                .addGap(21, 21, 21)
                                .addComponent(qtdRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscaProduto)))
                                .addGap(18, 18, 18)
                                .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(totalTxt)
                        .addGap(35, 35, 35)
                        .addComponent(RegistrarPedido)
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AdicionarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RemoverProd, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AdicionarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RemoverProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtdRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totalTxt)
                            .addComponent(RegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverProdActionPerformed
        int linhaSelecionada = tabelaProdutosReservados.getSelectedRow();
        ReservaProduto rp = new ReservaProduto();
        ListIterator listIt = this.listaReserva.listIterator();
        Produto produto = new Produto();
        int posicao = 0;

        if (linhaSelecionada >= 0) {
            if ((int) qtdRemover.getValue() > 0) {
                rp = this.modelRP.get(linhaSelecionada);
                if ((int) qtdRemover.getValue() <= rp.getQuantidade()) {
                    produto = rp.getProduto();
                    String cliente = this.reserva.getCliente().getNome();
                    String nomeProd = produto.getNome();
                    rp.setProduto(produto);
                    produto.setQntAtual(produto.getQntAtual()+(int) qtdRemover.getValue());
                    while (listIt.hasNext()) {
                        posicao++;
                        ReservaProduto rpIt = (ReservaProduto) listIt.next();
                        if (rpIt == rp) {
                            posicao--;
                            listIt.remove();
                            break;
                        }
                    }

                    if ((int) qtdRemover.getValue() < rp.getQuantidade()) {
                        rp.setQuantidade(rp.getQuantidade() - (int) qtdRemover.getValue());
                        rp.setPreco(rp.getPreco() - (int) qtdRemover.getValue() * produto.getPrecoVenda());
                        listaReserva.add(posicao, rp);
                        this.reserva.setPreco(this.reserva.getPreco() - produto.getPrecoVenda() * (int) qtdRemover.getValue());
                    } else {
                        this.reserva.setPreco(this.reserva.getPreco() - produto.getPrecoVenda() * rp.getQuantidade());
                    }

                    this.modelRP = new ReservaProdutoTableModel(this.listaReserva);  //atualiza a tabela
                    tabelaProdutosReservados.setModel(this.modelRP);
                    

                    totalTxt.setText("" + this.reserva.getPreco());
                    tabelaProduto.repaint();
                }
                else{
                    JOptionPane.showMessageDialog(this, "A quantidade a ser removida é invalida.", "Erro.", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "A quantidade a ser removida deve ser superior a zero.", "Erro.", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto.", "Erro: Nenhum Produto selecionado.", JOptionPane.ERROR_MESSAGE);
        }
        qtdRemover.setValue(0);
    }//GEN-LAST:event_RemoverProdActionPerformed

    private void RegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPedidoActionPerformed
        if (this.reserva.getPreco() <= 0){
            JOptionPane.showMessageDialog(this, "Reserva " + this.reserva.getId() + " não possui preço. Por isso não será cadastrada.", "Compra não cadastrada.", JOptionPane.INFORMATION_MESSAGE);
            new Reservass().setVisible(true);
            this.dispose();
        }else{
            int opcao = JOptionPane.showConfirmDialog(this, "Voce tem certeza que deseja cadastrar esta reserva?", "Confirmar Reserva.", JOptionPane.YES_NO_OPTION);
            if (opcao == YES_OPTION) {
                this.controleReserva.alterarReserva(this.reserva);

                controleRP.cadastrarRP(listaReserva);
                new Reservass().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_RegistrarPedidoActionPerformed

    private void AdicionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarProdActionPerformed
        int linhaSelecionada = tabelaProduto.getSelectedRow();
        ReservaProduto rp = new ReservaProduto();
        Produto produto = new Produto();
        ListIterator listIt = this.listaReserva.listIterator();
        int posicao = 0;

        if (linhaSelecionada >= 0) {
            if (((int) qtdProduto.getValue() > 0)){
                produto = this.modelProduto.get(linhaSelecionada);
                if((int) qtdProduto.getValue() <= produto.getQntAtual()){
                    rp.setProduto(produto);
                    rp.setReserva(this.reserva);
                    rp.setQuantidade((int) qtdProduto.getValue());
                    rp.setPreco((int) qtdProduto.getValue() * produto.getPrecoVenda());
                    produto.setQntAtual(produto.getQntAtual() - rp.getQuantidade());
                    while (listIt.hasNext()) {
                        posicao++;
                        ReservaProduto rpIt = (ReservaProduto) listIt.next();
                        if (rpIt.getProduto().getId() == produto.getId()) {
                            posicao--;
                            rp.setQuantidade(rp.getQuantidade() + rpIt.getQuantidade());
                            rp.setPreco(rp.getPreco() + rpIt.getPreco());
                            reserva.setPreco(reserva.getPreco() - rpIt.getPreco());
                            listIt.remove();
                            break;
                        }
                    }

                    this.listaReserva.add(posicao, rp);
                    this.modelRP = new ReservaProdutoTableModel(this.listaReserva);
                    tabelaProdutosReservados.setModel(this.modelRP);
                    this.reserva.setPreco(this.reserva.getPreco() + rp.getPreco());
                    totalTxt.setText("" + this.reserva.getPreco());
                    tabelaProduto.repaint();
                }
                else {
                    JOptionPane.showMessageDialog(this, "A quantidade do produto selecionados é maior que a a quantidade em estoque.", "Erro.", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "A quantidade do produto deve ser superior a zero.", "Erro.", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto.", "Erro: Nenhum Produto selecionado.", JOptionPane.ERROR_MESSAGE);
        }
        qtdProduto.setValue(0);
    }//GEN-LAST:event_AdicionarProdActionPerformed

    private void buscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProdutoActionPerformed

    private void buscaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaProdutoKeyReleased
        this.produtoNome = buscaProduto.getText();
        this.listaProd = controleProd.listarProdutos(this.produtoNome);
        this.modelProduto = new ProdutoTableModel(this.listaProd);
        tabelaProduto.setModel(this.modelProduto);
    }//GEN-LAST:event_buscaProdutoKeyReleased

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        new Reservass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarProd;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton RegistrarPedido;
    private javax.swing.JButton RemoverProd;
    private javax.swing.JTextField buscaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner qtdProduto;
    private javax.swing.JSpinner qtdRemover;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTable tabelaProdutosReservados;
    private javax.swing.JLabel totalTxt;
    // End of variables declaration//GEN-END:variables
}
